export const POST_COMPANY = "POST_COMPANY";
export const GET_INDIVIDUAL_COMPANY = "GET_INDIVIDUAL_COMPANY";
export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";